In [1]:
import numpy as np

In [2]:
import pandas as pd

In [4]:
1 == '1'

False

In [5]:

10 % 2

0

In [6]:
11 % 2

1

In [7]:
number = 11



In [10]:
def is_even(number):
    if (number % 2 == 0):
        print("the number is even")
    else:
        print("this number is odd")

In [13]:
is_even(3)

this number is odd


In [14]:
values = [True, True, True, False]

In [21]:
counter = 0

for v in values:
    #print(counter)
    if v == True:
        print('It is true')
    else:
        print("it is false")
        print(counter)
    counter = counter + 1
    

It is true
It is true
It is true
it is false
3


In [22]:
values[3]

False

In [27]:
def c_to_f(temp):
    return 9/5 * temp + 32

In [23]:
temperatures = ["32C", "7F", "15C", "8C"]

In [35]:
new_list = []

for t in temperatures:
    #print(t)
    #print(t[-1])
    last_character = t[-1]
    if last_character == 'C':
        sliced = t[:-1]
        sliced = float(sliced)
        temp_in_fahr = c_to_f(sliced)
        temp_in_fahr = str(temp_in_fahr)
        temp_in_fahr = temp_in_fahr + 'F'
        #print(temp_in_fahr)
        new_list.append(temp_in_fahr)
    else:
        #print(t)
        sliced = t[:-1]
        sliced = float(sliced)
        new_list.append(str(sliced)+'F')
new_list

['89.6F', '7.0F', '59.0F', '46.4F']

In [36]:
import math

In [37]:
math.pi

3.141592653589793

In [38]:
radius = 10
2 * math.pi * radius

62.83185307179586

In [39]:
def area_circle(radius):
    return 2 * math.pi * radius

In [40]:
area_circle(10)

62.83185307179586

In [43]:
temp = [30, 50, 70]
np_temp = np.array(temp)
(9/5) * np_temp + 32

array([ 86., 122., 158.])

In [44]:
sample = np.array([1, 2, 3, 4, 5])

In [45]:
sample

array([1, 2, 3, 4, 5])

In [48]:
list_idx = [0]
sample[list_idx]

array([1])

In [49]:
sample[0]

1

In [50]:
numbers = range(1, 6)

In [53]:
numbers = np.array(numbers)

In [54]:
numbers

array([1, 2, 3, 4, 5])

In [55]:
list_idx = [0, -1]

In [56]:
numbers[list_idx]

array([1, 5])

In [57]:
list_idx = [True, False, False, False, True]
numbers[list_idx]

array([1, 5])

In [72]:
np_weight = np.array([60, 70, 50, 60, 60])
np_height = np.array([1.2, 1.5, 1.7, 1.9, 2.0])

In [76]:
condition = (np_weight <= 70)

In [77]:
condition

array([ True,  True,  True,  True,  True])

In [78]:
np_height[condition]

array([1.2, 1.5, 1.7, 1.9, 2. ])