In [20]:
import numpy as np

In this homework, all of the solutions must be developed as a **function**.

Some exercises will be sequential, which means you will have to use **functions** made in previous exercises, to solve them.

# Exercise 1  - Euler


If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

Find the sum of all the multiples of 3 or 5 below 1000.


In [8]:
def euler_sum(limit):
    ____
euler_sum(1000)

233168

# Exercise 2 - Is number even

Build a function that returns `True` if the provided number is even, and `False` is the number is odd.

In [9]:
def is_even(number):
    ____
is_even(2)

True

# Exercise 3 - Fibonnaci Lists



Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Return the Fibonnaci sequence for numbers less than 1000.

In [13]:
def fibonnaci(limit):
    ___
fibonnaci(1000)

[1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987]

# Exercise 4 - Fibonnaci Even Sum

By considering the terms in the Fibonacci sequence whose values do not exceed 1000, find the sum of the even-valued terms.

Use the function developed on exercise 2 to have a the Fibonnaci sequence, and the function of exercise 2 to find out if the number is even.

In [14]:
def even_fibonnaci_sum(limit):
    ___
even_fibonnaci_sum(1000)

798

# Exercise 5 - Power digit sum

$2^{15}$ = 32768 and the sum of its digits is 3 + 2 + 7 + 6 + 8 = 26.

What is the sum of the digits of the number $2^{1000}$?

**`[HINT]`**: We can convert a `str` to a list of characaters by doing `list(str)`

In [18]:
def power_digit_sum(num):
    ___
power_digit_sum(2**1000)

1366

# Exercise 6 - Even Numpy Array

We can use `np.array` to do **element-wise** operations and math.

Do a function that takes a `np.array` as an argument and returns an **array of booleans** (array of `True` or `False` values) with `True` if the number is even, and `False` otherwise.

In [30]:
def even_np_array(arr):
    ___
even_np_array(np.array([1, 2, 3]))

array([False,  True, False])

# Exercise 7 - Numpy Array all even

Taking the result from the previous function, do another function that returns `True` if all the values in the array are `True` and `False` otherwise.

In [29]:
def array_all_even(arr):
    ___
array_all_even(np.array([1, 2, 3]))

False

# Exercise 8 - Replace even numbers with -1

Using the function made in exercise 7, replace all the even numbers in the array by -1.

**`[HINT]`**: We can use an **array of booleans** (`True` or `False`) to **subset** an array.

In [33]:
arr = np.array([1,2,3])
arr[[True, False, False]]

array([1])

**`[HINT]`**: With the **subset** of the array we can replace the given values

In [35]:
arr[[True, False, False]] = 9000
arr

array([9000,    2,    3])

In [32]:
def replace_even_with_minus_1(arr):
    ___
replace_with_minus_1(np.array([1, 2, 3]))

array([ 1, -1,  3])